### ISSUE TITLE
Contract support for adapters

### ISSUE THREAD

**Issue by Flowlessx** [tronprotocol/tronwallet-adapter#26]
smart contract error WalletSignTransactionError: Cannot read properties of undefined (reading 'contract')
    at TronLinkAdapter.eval (adapter.js:340:1)
    at Generator.throw (<anonymous>)
    at rejected (adapter.js:5:42)

I can sign all other transactions beside contract transactions (trc20 & trc721)

**Comment by Flowlessx** [comment]
```
async function trc721_transferFrom() {
    try {
      if (!connected) {
        console.error('Wallet not connected.');
        return;
      }
      
      console.log("connected " + connected)
      console.log("address " + address);
      console.log("contract " + trc721ContractAddress);
      console.log("receiver " + receiver);
      console.log("adapter " + adapter.connected);
      var parameter = [
        {
          type:'address',
          value: receiver },
        {
          type:'uint256',
          value: 5
        }
      ];

      var options = {
        feeLimit:100000000,
      };

      var unSignedTransaction = await tronWeb.transactionBuilder.triggerConstantContract(
        trc721ContractAddress,
        'baseURI()',
        options,
        parameter,
        adapter.address      
      );
      const signedTransaction = await adapter.signTransaction(unSignedTransaction);

      console.log("signed transaction" + signedTransaction);
      await adapter.tronWeb.trx.sendRawTransaction(signedTransaction);
      console.log('- transferFrom hash:', signedTransaction, '\n');
      setOpen(true);
    } catch (error) {
      console.error('trigger smart contract error', error);
    }
  }
```

**Comment by alienzhangyw** [comment]
The docs and demos are wrong.
```javascript
const signedTransaction = await adapter.signTransaction(unSignedTransaction.transaction);
const res = await tronWeb.trx.sendRawTransaction(signedTransaction);
console.log('- transferFrom hash:', res.txid, '\n');
```

**Comment by way2ex** [comment]
Apologize for any inconvenience. Thanks for the reply by @alienzhangyw .

This issue occurs because the returned value of  `tronWeb.transactionBuilder.sendTrx` is different from `tronweb.transactionBuilder.triggerSmartContract`. The later wrapped `unsignedTransaction` in an object like :
```
{
    result: { result: true },
    transaction: {...}
}
```
